gather_cnv
gather_cnv_ssp

We intentionally look in all the namespaces, even though
we expect to have them in the `openshift` namespaces, to get
a clue about weird states (e.g. duplicated or misplaced templates)
Signed-off-by: Francesco Romani <fromani@redhat.com>

ssp: gather CNV templates

---

gather_cnv_nodes

Gather NetworkManager journal from nodes.
Logs for additional units can be collected by adding them to NODE_UNITS

Collect journal logs on nodes

---

collection-scripts/gather_nodes
node-gather/Dockerfile

brctl is not available due to bridge-utils being deprecated. Suggested replacement is `bridge link` from iproute which is already used in the container.

bridge-utils not available on rhel8

---

collection-scripts/gather_nodes

During work on bridge-utils removal we discovered that we are not
collecting information about vlans. This PR adds it.

Add vlan info collection

---

node-gather/Dockerfile

Since OVS logs and configuration are collected by openshift-must-gather,
we can remove this dependency from kubevirt must-gather.

Remove openvswitch dependency

---

collection-scripts/gather

The PR gathers the ImageStream data as requested [here](https://projects.engineering.redhat.com/browse/OSBS-7820?focusedCommentId=1693239&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1693239)
Quote:
> As a quality engineer, I am testing a complex product on a pre-deployed cluster. I can use podman to tell which image digest is running on my node. I would like to look it up somewhere (say, in brewweb) and find the NVR of the build to which it belongs, who built it and when.

Gather ImageStreamTags

---

collection-scripts/gather_crs

CRs might be namespace scoped or cluster scoped and must-gather should
collect all and place into expected folders.
Fixes #34

Collect cluster CRs

---

collection-scripts/gather

Preparing for patch:
https://github.com/kubevirt/cluster-network-addons-operator/pull/233
As a second step we should remove the obsoleted namespaces.

Gather namespace cluster-network-addons

---

collection-scripts/gather_nodes

Since gather_nodes is running in the context of a cluster, no need to
attempt a login (which failed since no server url was provided)

Remove unnecessary login

---

collection-scripts/gather_nodes

When running must-gather with multiple images, resolving the node-gather
image failed. The patch suggests a unique method to identify the pod
that should be used for setting node-gather image.

Resolve node-gather image

---

Dockerfile
collection-scripts/gather_nodes

In order not to exceed overall must-gather time limit, the scheduling of
node-gather pods should be limited to allow collection of data from pods
that were able to get scheduled.
The openshift/origin-must-gather image version is set for 4.2.0, since
in version 4.3.0 the openshift-must-inspect was depracated and causes
failures that should be addressed separatedly.

Limit node-gather pod scheduling time

---

collection-scripts/gather_hco

Gathering the packages one by one takes a long time which can cause must-gather to time out. This way is much faster.

Changed how packagemanifests are gathered

---

Makefile
README.md

`MUST_GATHER_IMAGE` should be required for running `make` to prevent accidental pushes to `quay.io/kubevirt/must-gather` by a user that has permissions to do so. In addition, in order to ensure that this functionality is documented, added a Development section to the README.md.

Made passing a MUST_GATHER_IMAGE mandatory and documented usage of it

---

.travis.yml

When pushing a PR for review, travis should attempt to build an image
but shouldn't push it to quay.io/kubevirt/must-gather.
Pushing an image should be done only on merge.
Fixes #66

Build on PR, push on merge

---

collection-scripts/gather_images
collection-scripts/gather_nodes
collection-scripts/gather_v2v

The must-gather command expects data to be printed out to the pod's log,
and if nothing is received within a given period of time, it will exit
on timeout.  If no data (expecting a newline) is received in the read
call, it may exit with unexpected EOF as well.
To overcome this, this patch speeds up the gathering of node data mainly
by moving all the sriov detection to a single oc exec call, and by
parallelizing gather_nodes.  It also adds some verbosity to
gather_images and removes the expr calls in v2v which displayed lines
containing the result of the expression.

Improved output for nodes, images and v2v

---

collection-scripts/gather_nodes

This is the same fix we committed recently here: https://github.com/openshift-kni/performance-addon-operators/pull/296
The must-gather logic we added for performance-addon-operator is
borrowed from the code here, so the fix may be relevant as well.
Signed-off-by: Francesco Romani <fromani@redhat.com>

must-gather: fix the ds readiness check

---

collection-scripts/gather_nodes

must-gather will fail on unexpected EOF when not receiving data from the
pod's log after ~60 seconds.
This patch will print a line while waiting for the node daemonset to be
ready every 10 seconds.

nodes: add verbosity when waiting for daemonset

---

collection-scripts/gather_nodes

oc must-gather does not use an init container anymore, so we have to
update the jsonpath to the new format, otherwise gathering data from
nodes will not work
Fixes bz#1848269

Updated the container image jsonpath

---

collection-scripts/gather

To understand why node network configuration fails, we should collect
policies and their enactments.
```release-note
Gather nmstate-releated NodeNetworkConfigurationPolicies and Enactments
```
Signed-off-by: Dan Kenigsberg <danken@redhat.com>

gather more nmstate-related objects

---

collection-scripts/gather
collection-scripts/gather_virtualmachines

**What this PR does / why we need it**:
This PR changes behaviuor how are yaml files of virtualmachines
saved. Previously virtualmachines were save to one folder. Now
virtualmachines are saved into separate folders based on if they
were created from common template or if they are custom created.
**Fixes**: https://bugzilla.redhat.com/show_bug.cgi?id=1966137
```
NONE
```
Signed-off-by: Karel Šimon <ksimon@redhat.com>

virtualmachines are sorted to custom and template-based

---

Dockerfile
collection-scripts/gather
collection-scripts/gather_hco

The installation namespace is hardcoded. This PR allows overriding it by setting another value in the Dockerfile.
The default namespace is `kubevirt-hyperconverged`.
```release-note
None
```

Allow overriding the CNV namespace for community deploymet

---

README.md
collection-scripts/gather_vms_details

1. The `VM` variable now also supports a comma-seperated list of VMs.
2. The new `VM_EXP` allows select VMs to gather their information, by a regex expression.
```release-note
Add two more option to gather VM information
1. The `VM` variable now also supports a comma-seperated list of VMs.
2. The new `VM_EXP` allows select VMs to gather their information, by a regex expression.
```

Add two more option to gather VM information

---

Dockerfile
automation/create_workloads.sh
collection-scripts/gather_virtualmachines
tests/validate_must_gather_test.go

Improve the gather_virtualmachines script by reducing the number of calls to the API-Server from 2 per VM, to 1 single call to get them all.
Fix bug in splitting VM yamls to custem and template based directory (BZ 1966137).
Allow writing to custom output in CI tests.
```release-note
Fix BZ 1966137
```

Improve the gather_virtualmachines script

---

Dockerfile
automation/create_workloads.sh
collection-scripts/gather_virtualmachines
tests/validate_must_gather_test.go

Improve the gather_virtualmachines script by reducing the number of calls to the API-Server from 2 per VM, to 1 single call to get them all.
Fix bug in splitting VM yamls to custem and template based directory (BZ 1966137).
Allow writing to custom output in CI tests.
```release-note
Fix BZ 1966137
```

[release-4.9] Improve the gather_virtualmachines script

---

tests/validate_must_gather_test.go

The `"should validate the nodes logs directories" test case in the functional test does not actually test anything, because the `Expect(fileInDir(nodeFiles, expectedResource))` check expects nothing.
This PR changes the test to check all the file and list the missing ones. If any file is missing, the test fails.
Also, the test now does not check the master nodes as daemon sets are not running there.
In addition, this PR does not look for the nft* files in the nodes, because they are missing as result of https://bugzilla.redhat.com/show_bug.cgi?id=2025750. #116 fixes this and will add the related new file to the test.
```release-note
None
```

Fix the validate nodes logs functional test

---

collection-scripts/gather_nodes
tests/validate_must_gather_test.go

Use the command `nft list ruleset` which prints all the nft tables,
instead getting table by table.
This way it is also not sensitive to bash parsing,
which split by words instead by lines,
causing the commands to fail collecting the tables.
Note that there will be one file `nftables` with all the tables,
instead one file per table.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2025750
Signed-off-by: Or Shoval <oshoval@redhat.com>
```release-note
None
```

nftables: Fix collecting nftables from nodes

---

collection-scripts/gather_vms_details
tests/validate_must_gather_test.go

Since virt-launcher doesn't have NET_ADMIN anymore,
we collect the info via the virt-handler by
entering the virt-launcher namespace.
In case nft binary exists, collect the rules using it,
else fallback to collect using iptables binary.
Fixes: 
https://bugzilla.redhat.com/show_bug.cgi?id=1959039
```release-note
None
```

network: Fix rule tables collecting

---

collection-scripts/gather_ns

Expected openshift namespace of sriov is
openshift-sriov-network-operator.
Update accordingly.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2030686
Signed-off-by: Or Shoval <oshoval@redhat.com>
```release-note
None
```

sriov: Update sriov namespace

---

collection-scripts/gather_vms_details

The bug ng bz-2059185: this bug is that the script takes the hole VM env var as a VM name, instead of cut it to multiple VMs
This PR fixes the bug.
```release-note
Fix bz-2059185
```

Fix bug where the script wrongly processed the VM var

---

README.md

Remove wrong commas from the examples in README.md, that fails the gathering of VM by regex.
```release-note
None
```

Fix misleading documentation

---

collection-scripts/gather_vms_details

Fixing BZ-2058925
The bug is where the script is trying to get the vm name from the virt-launcher pod name. The script assumes that the pod name is the vm name with a random addition, separated by a dash. But that is not true for VMs with to long name, and in this case the pod name is not exactly that; e.g. it lack the dash, and the last few characters.
This PR fixes the bug by using different approach to get the VM name from the virt-launcher pod: it reads the `kubevirt.io/domain` annotation in the pod, assuming this is the VM name.
```release-note
Fix BZ-2058925
```

Fix bug, where the gather_vms_details script fails to collect VM with long names

---

automation/deploy_hco.sh

The test is failing from time to time, to deploy CNV. This PR check if the deployments exist before trying to check their status.
```release-note
None
```

Fix the E2E test

---

collection-scripts/gather_ns

Must-gather output shows "Error from server (NotFound): namespaces" when it tries to collect information about namespaces only present in plain Kubernetes installations.
```release-note
Remove from collection namespaces of plain Kubernetes installations
```

Remove from collection namespaces of plain Kubernetes installations

---

collection-scripts/gather_vms_details

Currently, must gather only collects the pod logs from the installation namespace when running the default gather script. When running the VM gather script, these logs were not being collected.
```release-note
Collect namespaces logs in gather_vms_details
```

Collect namespaces logs in gather_vms_details

---

Dockerfile

Noticed when trying to build a local image for tests, that `docker build` was failing while installing dependencies:
```
Step 8/13 : RUN dnf update -y &&     dnf install iproute tcpdump pciutils util-linux nftables rsync -y &&     dnf clean all
---> Running in e9b8f09c8d32
CentOS Linux 8 - AppStream                      135  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c dnf update -y &&     dnf install iproute tcpdump pciutils util-linux nftables rsync -y &&     dnf clean all' returned a non-zero code: 1
make: *** [Makefile:16: docker-build] Error 1
```
Also noticed that this issue also happened in the [last GitHub build and push image …

Use centos:stream8 in Dockefile

---

collection-scripts/gather_vms_details

This bug was partially fixed before, but not when reading specific
VNs.
This PR also fix the bug for named VMs.
```release-note
Fix BZ 2058925
```

Fix BZ 2058925: failed to get detailed for VMs with long names

---

Makefile

When running tests in an automated way it would be nice to abstract how tests are built and executed and just be able to run `make test`. Also the recent #141 changes how these steps are done when comparing, for example with `release-4.10`, which would require different test script configurations for each version when not just using something like `make test`.
```release-note
None
```

Add test commands to Makefile

---

automation/delete_workloads.sh

When testing `must-gather` in pre-existing clusters it would be useful to have a way to cleanup created workloads used for validation.
```release-note
None
```

Add script to delete tests workloads

---

collection-scripts/gather_ns

Manual cherry-pick of #130 
Must-gather output shows "Error from server (NotFound): namespaces" when it tries to collect information about namespaces only present in plain Kubernetes installations.
```release-note
Remove from collection namespaces of plain Kubernetes installations
```

[release-4.9] Bug 2086898: Remove from collection namespaces of plain Kubernetes installations

---

collection-scripts/gather_vms_details
tests/validate_must_gather_test.go

gather_vms_details: adapt to rootless virt-launcher
1. The root virt-launcher is saving qemu logs under
/var/log/libvirt/qemu/
while the rootless one under
/var/run/libvirt/qemu/log/
logs for long running VMs are periodically rotated
as .0, .1 and so on.
Try to always collect whatever is readable.
2. Fix the mechanism used to identify the PID
of virt-launcher process to work also
with rootless virt-launcher
3. Fix functional tests to ensure we always
get a not zero bytes long logs from VMs.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2076379
```release-note
gather_vms_details: adapt to rootless virt-launcher
```

gather_vms_details: adapt to rootless virt-launcher

---

collection-scripts/gather_vms_details

With virt-launcher images built after
https://github.com/kubevirt/kubevirt/pull/7713,
qemu logs are available in
/var/run/kubevirt-private/libvirt/qemu/log/
Try to collect also the content of that folder.
Continue collecting previous paths for backward
compatibility with virt-launcher images
built in the past.
Start testing with hco 1.8.0-unstable to
test with up to date bits.
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
```release-note
Try to collect qemu logs also from another path
```

Try to collect qemu logs also from another path

---

README.md
collection-scripts/gather
collection-scripts/gather_instancetypes

This change introduces basic collection support for the following CRDs:
- VirtualMachineInstancetype
- VirtualMachineClusterInstancetype
- VirtualMachinePreference
- VirtualMachineClusterPreference
```release-note
The instancetype API CRDs `VirtualMachineInstancetype`, `VirtualMachineClusterInstancetype`, `VirtualMachinePreference and `VirtualMachineClusterPreference` are now collected.
```

Add instancetype support

---

collection-scripts/gather_ns

This is helpful in debugging clones from golden images, which is definitely a common flow
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
**Maintainer note**:
Should we differentiate upstream/downstream and also log the community version of `openshift-virtualization-os-images`?
```release-note
Add logging of golden image namespace
```

Log golden images namespace as well for debugging

---

automation/deploy_hco.sh
node-gather/node-gather-ds.yaml
tests/validate_must_gather_test.go

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2162503
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
```release-note
Execute node-gather pod also on master nodes
```

Execute node-gather pod also on master nodes

---

.github/workflows/pr-sanity.yaml
README.md
collection-scripts/common.sh
collection-scripts/gather
collection-scripts/gather_apiservices
collection-scripts/gather_cdi
collection-scripts/gather_crds
collection-scripts/gather_crs
collection-scripts/gather_hco
collection-scripts/gather_images
collection-scripts/gather_instancetypes
collection-scripts/gather_nodes
collection-scripts/gather_ns
collection-scripts/gather_resources
collection-scripts/gather_ssp
collection-scripts/gather_virtualmachines
collection-scripts/gather_vms_details
collection-scripts/gather_vms_namespaces
collection-scripts/gather_webhooks
collection-scripts/logs.sh

We occasionally still get must-gather archives
which contains only a subset of the desired information so I think its usage is still not so intuitive.
Let's try to simplify even more:
1. single entry point script: all the collectors scripts will generate a clear error if directly executed: 
```
This script should not be directly executed.
Please check "/usr/bin/gather --help" for execution options.
```
2. always execute the mandatory collectors without the need to remember to explicitly add --default option
3. reduce the number of CLI options keeping there only optional collectors
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
```release-note
Simplify must-gather usage
```

Simplify must-gather usage

---

collection-scripts/gather_ns

As of now, it's trying to get the inspect only from ns/openshift-sdn. Find the cluster network type and collect either openshift-sdn or openshift-ovn-kubernetes based on the network type.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2214503
```release-note
Collect openshift-ovn-kubernetes on OVN OCP clusters
```

Collect openshift-ovn-kubernetes on OVN OCP clusters

---

collection-scripts/gather_vms_details

bridge-utils was deprecated in rhel 7 and was removed in rhel 8. Use bridge link show instead of brctl show.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2216449
```release-note
Substitute brctl show with the bridge Command
```

Use bridge command instead of brctl

---

collection-scripts/gather_vms_details

If the VMs are live migrated, there will be source virt-launcher pods with status "completed". So oc exec will fail on these pods with error "cannot exec into a container in a completed pod". This results in many empty files under `vms/<vm-name> ` if the VM was migrated multiple times. So run gather_vm_info only for "running" pods.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2216447
```release-note
Collect VM data only from running virt-launcher pods
```

Don't Collect VM data from completed virt-launcher pods

---

collection-scripts/gather_vms_details
tests/validate_must_gather_test.go

Extend kubevirt must-gather collection to collect more info with virsh command.
Which issue(s) this PR fixes:
https://issues.redhat.com/browse/CNV-26740
```release-note
Added capabilities.xml
Added domcapabilities.xml
Added list.txt 
Added domblklist.txt 
Added domjobinfo.txt
Added blockjob.txt
```

Add details about VMs using virsh

---

Dockerfile
README.md
automation/deploy_hco.sh
collection-scripts/gather
collection-scripts/gather_instancetypes
tests/validate_must_gather_test.go

This PR does the following:
- Enable the collection of `instancetypes` by default.
- Collect `controllerrevisions` that are associated with VMs. `controllerrevisions` are useful as they contain a point in time of the associated instance type or preference that may have been mutated or deleted. For example, when an instance type is patched, an associated VM won't get updated, unless requested explicitly, as it points to the older `controllerrevision`. For more information, PTAL at https://kubevirt.io/user-guide/virtual_machines/instancetypes/#versioning.
- Fix typo in `virtulmachineclusterinstancetype`
- Bump OCP must-gather image to 4.13 and HCO to 1.9.0.
Jira-ticket: https://issues.redhat.com/browse/CNV-30758
```release-note
Enable the collection of instancetypes by …
```

Handle the introduction of instancetypes

---

automation/create_workloads.sh

Add sleep to the create_workloads.sh

---

automation/create_workloads.sh

The e2e test fails from time to time, waiting for vmi that was not created yet.
This PR changes the script so it will retry reading the vmi before waiting for it to be ready.
```release-note
None
```

Add sleeps to automation/create_workloads.sh

---

automation/create_workloads.sh

The e2e test fails from time to time, waiting for vmi that was not created yet.
This PR changes the script so it will retry reading the vmi before waiting for it to be ready.
```release-note
None
```

[release-412] Add sleeps to automation/create_workloads.sh

---

collection-scripts/gather
collection-scripts/gather_virtualization
tests/validate_must_gather_test.go

Collect the number of running virtual machines in the cluster, across all namespaces.
Jira-ticket: https://issues.redhat.com/browse/CNV-32855
/cc @sradco, @nunnatsa  
```release-note
Collect the number of running virtual machines in the cluster.
```

Collect running VMs count

---

collection-scripts/version

[must-gather enhancement document](https://github.com/openshift/enhancements/blob/master/enhancements/oc/must-gather.md#must-gather-images) recommends using file named "version"
```release-note
Rename version file to adhere to requirements
```

Rename file from version.txt to version

---

collection-scripts/common.sh
collection-scripts/gather_cdi
collection-scripts/gather_crds
collection-scripts/gather_instancetypes
collection-scripts/gather_nodes
collection-scripts/gather_ns
collection-scripts/gather_resources
collection-scripts/gather_vms_details
collection-scripts/gather_vms_namespaces
tests/validate_must_gather_test.go

see: https://github.com/openshift/must-gather/pull/400
```release-note
use must-gather since and since time env vars on inspect cmds
```

use must-gather since and since time env vars on inspect cmds

---

.github/workflows/pr-sanity.yaml
Makefile
collection-scripts/version

- Bump shellcheck to v0.10.0
- explicitly disable SC2317 since it's reporting
many false positives for us (we have helper functions
that are only indirectly called in subshells for
parallel executions but shellcheck is currently not able
to follow them and so it's reporting the commands
in the helper functions as unreachable)
```release-note
NONE
```

Bump shellcheck to v0.10.0

---

tests/validate_must_gather_test.go

```release-note
add test ID for test validate the running VMs count in virtualizationDir must-gather
```

add test ID for test verify the running VMs count must-gather
