Dockerfile, gather_cnv, gather_cnv_nodes, node-gather/Dockerfile, node-gather/node-gather-crd.yaml, node-gather/node-gather-ds.yaml
This change will gather the information from all the nodes.
=> Gather nodes information

gather_cnv, gather_cnv_cdi
Added CDI namespace and collection script. 
Signed-off-by: Alexander Wels <awels@redhat.com>
=> Add CDI collection scripts

gather_cnv, gather_cnv_apiservices, gather_cnv_crs, gather_cnv_vms_details
add/enhance gathering scripts to collect more kubevirt core resources.
still WIP:
- scripts works in isolation, but I want to test the bundle e2e (e.g. to avoid dupes)
- I want to test against a real populated cluster, so far I'm checking against mostly empty clusters.
=> Must gather virt core

gather_cnv, gather_cnv_nodes, gather_cnv_webhooks
We gather the webhooks configuration, and (again) the services they
refer to.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> virt: gather infos about webhooks

collection-scripts/gather, collection-scripts/gather_images
The script will manually collect image related data.
This is a workaround until an issue with collectin imagestreamtags by openshift
is mended: https://github.com/openshift/must-gather/issues/122
=> Add script to collect image data

collection-scripts/gather
CNV 2.1 is using openshift-cnv ns.  Collect the logs from there.
=> Collect logs from openshift-cnv namespace

collection-scripts/gather_nodes, node-gather/node-gather-ds.yaml
Openshift cni bins and configs can reside in:
- /etc/kubernetes/cni/net.d
- /var/lib/cni/bin
These should be collected along with the kubernetes dirs.
=> Additional config dirs for cni plugins

collection-scripts/gather, collection-scripts/gather_hco
In order to debug HCO related failures
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
=> Add gather_hco

collection-scripts/gather_cdi, collection-scripts/gather_nodes
There are messages that could be skipped and cleared from the output of
must-gather.
=> Reduce noise from must-gather output

collection-scripts/gather_nodes, collection-scripts/gather_vms_details
=> Clear errors from must-gather output

scripts/bugzilla_attach.py
You can now use multiple images and image-streams. The syntax for these is identical to that of the must-gather: use the `--image=` or `--image-stream=` flags multiple times to provide multiple images.
If no image or image-stream was provided, the script still defaults to `quay.io/kubevirt/must-gather`
=> Added support for multiple images and image stream

Dockerfile, collection-scripts/gather, collection-scripts/gather_cdi, collection-scripts/gather_crds, collection-scripts/gather_v2v, collection-scripts/gather_vms_namespaces
=> Changed `openshift-must-gather` to `oc adm inspect`

.travis.yml
Added encrypted credentials for the quay.io/kubevirt/must-gather repository. Merged PRs will automatically trigger a build and push to there (if the build succeeds).
=> Added credentials for travis automation

collection-scripts/gather_images, node-gather/node-gather-ds.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1816778 by updating the api.
Also fixes a bug where the images directory was not being created
=> Updated node-gather API and fixed minor image bug

collection-scripts/gather, collection-scripts/gather_v2v
=> Collect VM import operator logs and resources

collection-scripts/gather_v2v
=> Direct pod logs of v2v to designated directory

collection-scripts/gather
=> Silent missing resources when gathering data

collection-scripts/gather
Also updated must-gather base image
=> Added nodes and machines to gathered resources, useful for NMO

OWNERS, OWNERS_ALIASES
=> Add owners

.travis.yml, Makefile, collection-scripts/gather, collection-scripts/gather_apiservices, collection-scripts/gather_cdi, collection-scripts/gather_crds, collection-scripts/gather_crs, collection-scripts/gather_hco, collection-scripts/gather_images, collection-scripts/gather_nodes, collection-scripts/gather_ssp, collection-scripts/gather_v2v, collection-scripts/gather_vms_details, collection-scripts/gather_vms_namespaces, collection-scripts/gather_webhooks
=> Added shellcheck on gather scripts

Dockerfile
```release-note
Rebase on origin:4.8.0 and centos:8
```
=> Rebase on origin:4.8.0 and centos:8

automation/create_workloads.sh, automation/deploy_hco.sh, automation/vm.yaml
1. use pre-built bundle to deploy HCO
2. create several VMs and run them, to check must-gather
```release-note
None
```
=> Improve automation

OWNERS_ALIASES
=> Update reviewer list

tests/main_test.go, tests/utils_test.go
=> Add Junit reporter to the CI tests

collection-scripts/gather_nodes, tests/validate_must_gather_test.go
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
=> Gather SELinux logs from nodes

Dockerfile, collection-scripts/gather, collection-scripts/gather_apiservices, collection-scripts/gather_cdi, collection-scripts/gather_crds, collection-scripts/gather_crs, collection-scripts/gather_hco, collection-scripts/gather_images, collection-scripts/gather_nodes, collection-scripts/gather_ns, collection-scripts/gather_ssp, collection-scripts/gather_virtualmachines, collection-scripts/gather_vms_details, collection-scripts/gather_vms_namespaces, collection-scripts/gather_webhooks, collection-scripts/logs.sh, collection-scripts/version
Also, added a version file to must-gather output
```release-note
Added a log file as part of must-gather output, named must-gather.log
Added version.txt with the must-gather version
```
=> Added a log file as part of must-gather output

automation/create_workloads.sh, collection-scripts/gather, collection-scripts/gather_crs, collection-scripts/gather_virtualmachines, tests/utils_test.go, tests/validate_must_gather_test.go
Collect the VM CRs by default
```release-note
Collect the VM CRs by default
```
=> Gather VM CR by default

collection-scripts/gather_crs, collection-scripts/gather_vms_details
```release-note
Collect basic VM info also from the gather_vms_details script
```
=> Collect basic VM info also from the gather_vms_details script

automation/create_workloads.sh, automation/ns.yaml, automation/vm.yaml, collection-scripts/gather, collection-scripts/gather_apiservices, collection-scripts/gather_cdi, collection-scripts/gather_crds, collection-scripts/gather_crs, collection-scripts/gather_hco, collection-scripts/gather_images, collection-scripts/gather_nodes, collection-scripts/gather_ns, collection-scripts/gather_ssp, collection-scripts/gather_v2v, collection-scripts/gather_virtualmachines, collection-scripts/gather_vms_details, collection-scripts/gather_vms_namespaces, collection-scripts/gather_webhooks, collection-scripts/logs.sh, collection-scripts/version, tests/utils_test.go, tests/validate_must_gather_test.go
```release-note
Bug fix
Logs added
```
=> [Release 4.9] Adopt the bug fixes and logs from the main branch

automation/create_workloads.sh, automation/ns.yaml, automation/vm.yaml, collection-scripts/gather, collection-scripts/gather_apiservices, collection-scripts/gather_cdi, collection-scripts/gather_crds, collection-scripts/gather_crs, collection-scripts/gather_hco, collection-scripts/gather_images, collection-scripts/gather_nodes, collection-scripts/gather_ns, collection-scripts/gather_ssp, collection-scripts/gather_v2v, collection-scripts/gather_virtualmachines, collection-scripts/gather_vms_details, collection-scripts/gather_vms_namespaces, collection-scripts/gather_webhooks, collection-scripts/logs.sh, collection-scripts/version, tests/utils_test.go, tests/validate_must_gather_test.go
```release-note
Bug fix
Logs added
```
=> [Release 4.8] Adopt the bug fixes and logs from the main branch

.github/workflows/pr-sanity.yaml, Makefile, collection-scripts/gather, collection-scripts/gather_apiservices, collection-scripts/gather_cdi, collection-scripts/gather_crds, collection-scripts/gather_crs, collection-scripts/gather_images, collection-scripts/gather_nodes, collection-scripts/gather_ns, collection-scripts/gather_ssp, collection-scripts/gather_virtualmachines, collection-scripts/gather_vms_details, collection-scripts/gather_vms_namespaces, collection-scripts/gather_webhooks, collection-scripts/logs.sh, collection-scripts/version
=> add shellcheck sanity github action

collection-scripts/gather_vms_details
```release-note
Fix the  gather_vms_details script
```
=> [Release 4.9] Fix the gather_vms_details, by exporting some env vars

collection-scripts/gather
Fixed duplicate entry.
Signed-off-by: Satyajit Bulage <sbulage@redhat.com>
```release-note
None
```
=> Removed redundant code

automation/deploy_hco.sh, tests/validate_must_gather_test.go
=> Update the HCO version in the e2e tests

OWNERS_ALIASES
Welcom @machadovilaca!
```release-note
None
```
=> Update the owner list

Makefile
Similar to #144 but for release-4.10
```release-note
None
```
=> [release-4.10] Add test commands to Makefile

collection-scripts/gather_ns
```release-note
Add default INSTALLATION_NAMESPACE to gather_ns
```
=> Add default INSTALLATION_NAMESPACE to gather_ns

Dockerfile
=> bump build env
